sudo: required
services:
        - docker
before_install:
        - docker build -t imagetestbuild -f Dockerfile.dev .
script:
        - docker run -e CI=true imagetestbuild npm run test -- --coverage
